ruby '2.2.3'
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.18', '< 0.5'
# Use Puma as the app server
# Setup server
gem 'passenger'


# Asset compilation and NPM modules
gem 'browserify-rails'
gem 'sass-rails'
gem 'uglifier'

# Setup react and dependencies
gem 'therubyracer', platforms: :ruby

# Graphql
gem 'graphql'
gem 'graphql-relay'

# Javascript routes
gem 'js-routes'

# Jquery turblinks
gem 'jquery-turbolinks'

# Authorization
gem 'pundit'

# User auth
gem 'devise'

# Bootstrap
gem 'bootstrap-sass', '~> 3.3.6'

#Speed up links
gem 'turbolinks', github: 'rails/turbolinks'

# Slug
gem 'stringex'

# Time
gem 'local_time'

# React
gem 'react-rails', '~> 1.5.0'


# Caching
gem 'rack-cache'
gem 'kgio'
gem 'dalli'

# Fake data
gem 'faker'

group :production do
  gem 'rails_12factor'
end

group :development do
  gem 'spring'
  gem 'web-console'
  gem 'foreman'
  gem 'figaro'
end
