# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14fcfb45a4dcf1667a246095de927de2ad4e2d4e92457a3bfeb9cd441af17334862fcd6c728aac618a1226fd2833c507f9a6f59f07c5c67d158bf3883fa4d0e6

test:
  secret_key_base: 0d0276425b6a724496f69b2d367bb0ad57d76c501930a848ed753ed94ac69977cd52280dc8b5d25c70875825e0a22d3e8d0e47578462c26f290d20057243d459

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
